In [3]:
import tensorflow as tf
import numpy as np

In [59]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b = np.array([[1, 0], [[1], [1]]], dtype=bool)

In [60]:
b

array([[ True, False],
       [ True,  True]], dtype=bool)

In [71]:
x = tf.placeholder('int32', [2, 2, 3])
y = tf.placeholder('bool', [2, 2])

In [77]:
t= tf.tile(tf.expand_dims(y,2), [1, 1, 3])

In [78]:
tf.expand_dims(y,2)

<tf.Tensor 'ExpandDims_14:0' shape=(2, 2, 1) dtype=bool>

In [79]:
t

<tf.Tensor 'Tile_11:0' shape=(2, 2, 3) dtype=bool>

In [80]:
p = tf.boolean_mask(x, t)

In [52]:
tf.expand_dims(x,2)

<tf.Tensor 'ExpandDims_6:0' shape=(2, 2, 1, 3) dtype=int32>

In [53]:
t

<tf.Tensor 'Tile_5:0' shape=(2, 2, 5, 3) dtype=int32>

In [39]:
flat = tf.contrib.layers.flatten(x)

In [54]:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="3"
sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
sess.run(tf.global_variables_initializer())                          

In [81]:
sess.run([p], feed_dict={x:a, y:b})

[array([ 1,  2,  3,  7,  8,  9, 10, 11, 12], dtype=int32)]

In [57]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
a[0][0]

array([1, 2, 3])

In [28]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])